<#
.SYNOPSIS
  Make a team's Copilot-style agents usable in OpenCode, and report on its skills.

.DESCRIPTION
  OpenCode v2 SILENTLY DROPS an agent file whose frontmatter it cannot use (measured on
  v2.0.10: a Copilot `tools: [...]` array or `model: GPT-5 (copilot)` makes the agent
  simply not exist -- no error, no log line). So the team repo is never linked raw.
  This script reads <TeamRepo>\agents\*.md and writes a cleaned copy of each into the
  global OpenCode agents folder:

    kept      description (or the first line of the body when there is none), the body
    dropped   name, tools, model, handoffs, target, argument-hint, everything else
    added     mode: subagent, steps, conservative permissions

  The team repo is only ever READ. Re-run after every `git pull` there; it is idempotent.
  Generated files carry a marker line. The script never overwrites a file without that
  marker (your own agents, the seven pipeline agents), and removes generated files whose
  source has disappeared.

  Skills need no conversion -- they are linked live through the `skills` key of
  opencode.jsonc -- so for skills this script only REPORTS what will not work.

.EXAMPLE
  .\sync-team-agents.ps1 -TeamRepo C:\repos\agent_and_skills
.EXAMPLE
  .\sync-team-agents.ps1 -TeamRepo C:\repos\agent_and_skills -WhatIf
#>
[CmdletBinding(SupportsShouldProcess)]
param(
  [Parameter(Mandatory)][string]$TeamRepo,
  [string]$ConfigDir = (Join-Path $env:USERPROFILE '.config\opencode'),
  [string]$AgentsSubdir = 'agents',
  [string]$SkillsSubdir = 'skills',
  [int]$Steps = 60
)
$ErrorActionPreference = 'Stop'
$Marker = 'generated by sync-team-agents.ps1'
$Pipeline = @('orchestrator', 'intake', 'researcher', 'planner', 'coder', 'reviewer', 'refactorer')
# Windows PowerShell 5.1 writes a BOM with -Encoding utf8, and a BOM in front of the
# opening `---` stops the frontmatter from being recognised. Always write without one.
$Utf8NoBom = New-Object System.Text.UTF8Encoding($false)

$TeamRepo = (Resolve-Path -LiteralPath $TeamRepo).Path
$src = Join-Path $TeamRepo $AgentsSubdir
$dest = Join-Path $ConfigDir 'agents'

# Returns @{ Front = <string[]>; Body = <string> }. Front is empty when the file has none.
function Split-Frontmatter([string]$text) {
  $lines = $text -split "`r?`n"
  if ($lines.Count -gt 0) { $lines[0] = $lines[0].TrimStart([char]0xFEFF) }
  if ($lines.Count -lt 2 -or $lines[0].Trim() -ne '---') { return @{ Front = @(); Body = $text.TrimStart([char]0xFEFF) } }
  for ($i = 1; $i -lt $lines.Count; $i++) {
    if ($lines[$i].Trim() -eq '---') {
      $body = ''
      if ($i + 1 -lt $lines.Count) { $body = ($lines[($i + 1)..($lines.Count - 1)] -join "`n") }
      return @{ Front = @($lines[1..($i - 1)]); Body = $body }
    }
  }
  return @{ Front = @(); Body = $text }   # unterminated frontmatter: treat it all as body
}

# Value of a top-level scalar key, including YAML block scalars (`key: >` / `key: |`).
function Get-FrontValue([string[]]$front, [string]$key) {
  for ($i = 0; $i -lt $front.Count; $i++) {
    if ($front[$i] -match "^$([regex]::Escape($key)):\s*(.*)$") {
      $v = $Matches[1].Trim()
      if ($v -match '^[>|][+-]?$') {
        $parts = @()
        for ($j = $i + 1; $j -lt $front.Count -and ($front[$j] -match '^\s+\S' -or $front[$j].Trim() -eq ''); $j++) { $parts += $front[$j].Trim() }
        $v = (($parts | Where-Object { $_ }) -join ' ')
      }
      if ($v.Length -ge 2 -and (($v[0] -eq '"' -and $v[-1] -eq '"') -or ($v[0] -eq "'" -and $v[-1] -eq "'"))) { $v = $v.Substring(1, $v.Length - 2) }
      return $v
    }
  }
  return $null
}

# Copilot semantics: no `tools` key means every tool; a `tools` list with nothing that
# can edit means a read-only agent.
function Test-CanEdit([string[]]$front) {
  $block = @(); $in = $false
  foreach ($l in $front) {
    if ($l -match '^tools:') { $in = $true; $block += $l; continue }
    if ($in) { if ($l -match '^\S') { break } else { $block += $l } }
  }
  if ($block.Count -eq 0) { return $true }
  return (($block -join ' ') -match '(?i)edit|write|create|new|apply|patch')
}

function Get-AgentId([string]$fileName) {
  $id = $fileName -replace '(?i)\.(agent|chatmode)\.md$', '' -replace '(?i)\.md$', ''
  $id = ($id.ToLowerInvariant() -replace '[\s_.]+', '-' -replace '[^a-z0-9-]', '' -replace '-{2,}', '-').Trim('-')
  return $id
}

function Test-Generated([string]$path) {
  if (-not (Test-Path -LiteralPath $path)) { return $false }
  return [bool](Get-Content -LiteralPath $path -TotalCount 40 | Select-String -SimpleMatch $Marker -Quiet)
}

# ---------------------------------------------------------------- agents
$written = 0; $skipped = 0; $removed = 0; $wanted = @{}
if (-not (Test-Path -LiteralPath $src)) {
  Write-Warning "No '$AgentsSubdir' folder in $TeamRepo - nothing to convert. (-AgentsSubdir to name another.)"
} else {
  if (-not (Test-Path -LiteralPath $dest)) { if ($PSCmdlet.ShouldProcess($dest, 'create folder')) { New-Item -ItemType Directory -Force -Path $dest | Out-Null } }
  foreach ($f in (Get-ChildItem -LiteralPath $src -Filter *.md -File -Recurse | Sort-Object FullName)) {
    $id = Get-AgentId $f.Name
    $rel = $f.FullName.Substring($TeamRepo.Length).TrimStart('\')
    if (-not $id) { Write-Warning "SKIP  $rel : cannot derive an agent id from the file name"; $skipped++; continue }
    if ($Pipeline -contains $id) { Write-Warning "SKIP  $rel : '$id' is one of the pipeline agents and is never replaced"; $skipped++; continue }
    if ($wanted.ContainsKey($id)) { Write-Warning "SKIP  $rel : id '$id' already produced from $($wanted[$id])"; $skipped++; continue }
    $target = Join-Path $dest "$id.md"
    if ((Test-Path -LiteralPath $target) -and -not (Test-Generated $target)) { Write-Warning "SKIP  $rel : $target exists and was not generated by this script"; $skipped++; continue }

    $parts = Split-Frontmatter ([System.IO.File]::ReadAllText($f.FullName))
    $body = $parts.Body.Trim("`r", "`n")
    $desc = Get-FrontValue $parts.Front 'description'
    if (-not $desc) {
      # No description: fall back to the first line of prose, then to the first heading.
      $prose = ($body -split "`r?`n" | Where-Object { $_.Trim() -and $_ -notmatch '^\s*(#|---|```|<!--)' } | Select-Object -First 1)
      $head = ($body -split "`r?`n" | Where-Object { $_ -match '^\s*#+\s+\S' } | Select-Object -First 1)
      if ($prose) { $desc = $prose.Trim() } elseif ($head) { $desc = ($head -replace '^\s*#+\s+', '').Trim() } else { $desc = "Team agent '$id'." }
      Write-Warning "NOTE  $rel : no description in frontmatter; using ""$desc"""
    }
    if ($desc.Length -gt 300) { $desc = $desc.Substring(0, 297) + '...' }
    $descYaml = '"' + ($desc -replace '\\', '\\' -replace '"', '\"') + '"'
    $edit = 'deny'; if (Test-CanEdit $parts.Front) { $edit = 'allow' }

    $out = @(
      '---'
      "description: $descYaml"
      'mode: subagent'
      "steps: $Steps"
      'permission:'
      "  edit: $edit"
      '  # OpenCode is opened in the ticket workspace; the code is outside it. v2''s default'
      '  # for outside paths is "ask", which a subagent cannot answer.'
      '  external_directory: allow'
      '  # web tools are not listed on purpose: the environment''s opencode.json decides'
      '  question: deny'
      '  task: deny'
      '  bash:'
      '    "*": allow'
      '    "git push*": deny'
      '    "git commit*": deny'
      '    "git * commit*": deny'
      '    "git * push*": deny'
      '    "git add*": deny'
      '    "git * add *": deny'
      '    "git reset --hard*": deny'
      '    "git checkout -- *": deny'
      '    "git clean*": deny'
      '    "rm -rf *": deny'
      '---'
      "<!-- $Marker from $($rel -replace '\\', '/') - edit the source, then re-run the sync -->"
      $body
      ''
    ) -join "`n"

    $wanted[$id] = $rel
    $old = $null; if (Test-Path -LiteralPath $target) { $old = [System.IO.File]::ReadAllText($target) }
    if ($old -ceq $out) { Write-Host "same  $id"; continue }
    if ($PSCmdlet.ShouldProcess($target, "write agent '$id' (edit: $edit)")) {
      [System.IO.File]::WriteAllText($target, $out, $Utf8NoBom)
      Write-Host "wrote $id  (edit: $edit)  <- $rel"; $written++
    }
  }
  # Generated files whose source is gone. Only files that carry the marker are touched.
  if (Test-Path -LiteralPath $dest) {
    foreach ($g in (Get-ChildItem -LiteralPath $dest -Filter *.md -File)) {
      $gid = [System.IO.Path]::GetFileNameWithoutExtension($g.Name)
      if ((Test-Generated $g.FullName) -and -not $wanted.ContainsKey($gid)) {
        if ($PSCmdlet.ShouldProcess($g.FullName, 'remove (source no longer exists)')) { Remove-Item -LiteralPath $g.FullName -Confirm:$false; Write-Host "gone  $gid"; $removed++ }
      }
    }
  }
}

# ---------------------------------------------------------------- skills (report only)
$skillRoot = Join-Path $TeamRepo $SkillsSubdir
$flat = @(); $noDesc = @()
if (Test-Path -LiteralPath $skillRoot) {
  $flat = @(Get-ChildItem -LiteralPath $skillRoot -Filter *.md -File)
  $all = @($flat) + @(Get-ChildItem -LiteralPath $skillRoot -Filter SKILL.md -File -Recurse | Where-Object { $_.DirectoryName -ne $skillRoot })
  foreach ($s in $all) {
    $p = Split-Frontmatter ([System.IO.File]::ReadAllText($s.FullName))
    if (-not (Get-FrontValue $p.Front 'description')) { $noDesc += $s.FullName.Substring($TeamRepo.Length).TrimStart('\') }
  }
  Write-Host ""
  Write-Host "skills: $($all.Count) found under $skillRoot ($($flat.Count) flat .md, $($all.Count - $flat.Count) <name>\SKILL.md)"
  foreach ($n in $noDesc) { Write-Warning "skill $n has no 'description:' - OpenCode loads it but never tells the model it exists. Add one in the team repo." }

  # Is the folder actually linked, and in the form that works?
  $cfg = @('opencode.jsonc', 'opencode.json') | ForEach-Object { Join-Path $ConfigDir $_ } | Where-Object { Test-Path -LiteralPath $_ } | Select-Object -First 1
  if (-not $cfg) { Write-Warning "no opencode.json(c) in $ConfigDir - the skills are not linked yet (install.ps1 -TeamRepo does that)." }
  else {
    $raw = [System.IO.File]::ReadAllText($cfg)
    $back = $skillRoot -replace '\\', '\\'          # as it appears inside JSON
    $fwd = $skillRoot -replace '\\', '/'
    if ($raw.IndexOf($back, [StringComparison]::OrdinalIgnoreCase) -ge 0) { Write-Host "skills: linked in $cfg" }
    elseif ($raw.IndexOf($fwd, [StringComparison]::OrdinalIgnoreCase) -ge 0) {
      if ($flat.Count -gt 0) { Write-Warning "skills are linked with FORWARD slashes in $cfg. On OpenCode v2.0.10 that collapses all $($flat.Count) flat skill files into one skill named '$SkillsSubdir'. Write the path as ""$back""." }
      else { Write-Host "skills: linked in $cfg" }
    }
    else { Write-Warning "skills folder is not listed under ""skills"" in $cfg. Add:  ""skills"": [""$back""]" }
  }
} else { Write-Host ""; Write-Host "skills: no '$SkillsSubdir' folder in $TeamRepo" }

Write-Host ""
Write-Host "agents: $written written, $removed removed, $skipped skipped -> $dest"
if ($written -or $removed) { Write-Host "Run 'opencode reload' when NO session is working (it aborts tool calls in flight), then check with 'opencode debug agents'." }
